DELETE http://localhost:3001/api/blogs/67803cbd3a8640667b4ef0d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRla2kiLCJpZCI6IjY3ODAzNTQ0ZThmOGI0MWIxZmQyOTZiNiIsImlhdCI6MTczNjUzODc3MCwiZXhwIjoxNzM2NTQyMzcwfQ.TzwHc0WtWe_Nvs5Psvmlek6109G9Jw-0iomnbzOmLu0
