GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRla2kiLCJpZCI6IjY3ODAzNTQ0ZThmOGI0MWIxZmQyOTZiNiIsImlhdCI6MTczNjUzODQ0OCwiZXhwIjoxNzM2NTQyMDQ4fQ.kEmMoBrbsqolh9ndlxb2OWSizpe7EW0YbnAkdydB2Ak